# @format

BOT:
  OWNERS: ["1252336351064490055","1193901323872120892","1207108142157275228"]
  ADMINS: ["1252336351064490055"]

LINKS:
  SUPPORT: "https://discord.gg/FW7JTMf7"
  MONGO_URI: "mongodb+srv://d3nj1x77:d3nj1x77@d3nj1x77.ljpwl0l.mongodb.net/?retryWrites=true&w=majority"

SPOTIFY:
  ID: "e6f84fbec2b44a77bf35a20c5ffa54b8"
  SECRET: "98f461b962443cfaf9539c610e2ea81"


FERO:
  PREFIX: "+"
  EMOJIS: "black"
  COLOR: "#9370DB"
  SHARDS: 1
  PER_CLUSTER: 1
  TOKEN: "MTI2OTcxMzUyNzAzNjQ0ODgyMg.GXMnh1.hUg6xvhrHMgn4ds3Kdy3tTyOcYoh3lU30ykKxs"
  VOTEURI: "https://top.gg/bot/1269713527036448822"
  TOPGGAUTH: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEyNjk3MTM1MjcwMzY0NDg4MjIiLCJib3QiOnRydWUsImlhdCI6MTcyMzIwNzY2OH0.TXAtgGirbkDGWZLCRcI4ZPgtiXCJbH-KOXXIfxRgbEs"


WEBHOOKS:
  ERROR: "https://discord.com/api/webhooks/1271813688726126712/48x6OZZbr-jzcB7Rl9JqB33tTulJIAOCsyeWxMVXlWEfVcMJkeZMoWgRSrY_2R-5sWOh"
  STATIC: "https://discord.com/api/webhooks/1271813684813107222/KH0JVr9zI4eUZbb3hZfAdJ4-JaAzOw5c7LfsglEfB7gsKUhkEIsuZLD7OwpUGzILjR4r"
  PLAYER: "https://discord.com/api/webhooks/1271814043874889748/Shv09vTDaqC_WBqSeTbHFEnR1-gqRsHCGhg_A__b7oMZrdvHpFDMkxG-UuM-mEVh9Upk"
  SERVER: "https://discord.com/api/webhooks/1271814175638945874/UQ-OgSIPdu7-hnjpCK-I_BhHEQf_bYu-DJPT_-jWcrG7-kyzaqoKUecR44J4wher1_V-"
  COMMAND: "https://discord.com/api/webhooks/1271814288041967626/eBePuoZSrYZq5gzAwkKqLQfwyPD7dtB5j47X2tv_wgBBaFgAr6LH7jz-lOC7FPdzauQW"

 